apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backend.name}}-svc
  namespace: {{.Values.metadata.namespace}}
  labels:
    app: {{.Values.backend.name}}
spec:
  selector:
    app: {{.Values.backend.name}}
  ports:
    - port: {{.Values.backend.service.port}}
      name: http
      targetPort: 8080
  type: NodePort