apiVersion: v1
kind: Service
metadata:
  name: {{.Values.ui.name}}-svc
  namespace: {{.Values.metadata.namespace}}
  labels:
    app: {{.Values.ui.name}}
spec:
  selector:
    app: {{.Values.ui.name}}
  ports:
    - port: 80
      name: http
      targetPort: 8081
  type: NodePort